remote_theme: ankitsultana/researcher@gem

title: Researcher
description: Deaf. Climbing lover. Passion for accessibility. Dream of traveling around the world. 
url: "https://ninakt.github.io"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: G-LJQLWSCQJ6 

footer: yes
footer_url: "https://github.com/ninakt"
footer_text: "Page design by Nina Tran"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Projects"
   link: "projects"
 - name: "Contact"
   link: "contact"
