remote_theme: ankitsultana/researcher@gem

title: Researcher
url: "https://ninakt.github.io"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Projects"
   link: "projects"
 - name: "Contact"
   link: "contact"
