remote_theme: ankitsultana/researcher@gem

title: Researcher
url: "https://ninakt.github.io"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

footer: yes
footer_url: "https://github.com/ninakt"
footer_text: "Page design by Nina Tran"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "assets/resume.pdf"
 - name: "CV"
   link: "assets/cv.pdf"
 - name: "Projects"
   link: "projects"
 - name: "Contact"
   link: "contact"
